spring:
  application:
    name: Academic Management System
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    show-sql: ${SPRING_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${SPRING_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8080}
